version: "3.8"
services:
  backend:
    image: backend:latest
    env_file:
      - .env
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    volumes:
      - ./logs:/logs
      - .:/usr/src/app
      - /usr/src/app/node_modules